[package]
name = "oom-alerter"
version = "0.1.0"
edition = "2021"
description = "Desktop notification daemon for pre-OOM memory pressure on Linux"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/jonjomckay/oom-alerter"
repository = "https://github.com/jonjomckay/oom-alerter"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
notify-rust = "4"
